/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static practice.TransactionParser.parseAmount;

class TransactionParserTest {
    @Test void parseAmountTest_success() {
        assertEquals(-100 ,parseAmount("100", "D"));
        assertEquals(100 ,parseAmount("100", "C"));
        assertEquals(0 ,parseAmount("0", "D"));
        assertEquals(0 ,parseAmount("0", "C"));
    }

    @Test void parseAmountTest_incorrectCreditDebitTypeCode() {
        assertThrows(NumberFormatException.class ,() -> parseAmount("C", "0"));
    }
}
